#spring:
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}

spring:
  jpa:
    hibernate:
      ddl-auto: update

# Example
#db:
#  url: jdbc:mysql://localhost:33066/bobashop
#  username: root
#  password: password1234

cron:
  expression: 0 0 0 * * *
#    0 */1 7-21 * * *